// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CIStr struct {
	_tab flatbuffers.Table
}

func GetRootAsCIStr(buf []byte, offset flatbuffers.UOffsetT) *CIStr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CIStr{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCIStr(buf []byte, offset flatbuffers.UOffsetT) *CIStr {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CIStr{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CIStr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CIStr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CIStr) O() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CIStr) L() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CIStrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CIStrAddO(builder *flatbuffers.Builder, o flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(o), 0)
}
func CIStrAddL(builder *flatbuffers.Builder, l flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(l), 0)
}
func CIStrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
